#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This file is automatically generated.

VERSIONS = [
    '2.3',
    '2.4',
    '2.5',
    '2.6',
    '2.7',
    '2.8',
]
STABLE_VERSION = '2.8'

DEFAULT_LANGUAGE = 'en'
LANGUAGES = ['en', 'fr']
