#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This file is automatically generated.

VERSIONS = [
    '2.3.2',
    '2.4',
    '2.4.1',
    '2.4.2',
    '2.4.4',
    '2.5',
    '2.5.1',
    '2.5.2',
]
LATEST_VERSION = '2.5.2'

DEFAULT_LANGUAGE = 'en'
LANGUAGES = ['en', 'fr']
