//////////////////////////////////////////////////////////////////////////
//                                                                      //
//    This file is automatically generated by the publish.py script.    //
//    Any changes made manually will be overwritten during the next     //
//    publish action.                                                   //
//                                                                      //
//////////////////////////////////////////////////////////////////////////
const default_language = 'en';
const stable_version = '2.5';
const versions = ['2.3', '2.4', '2.5'];
var vcount = versions.length;
var i, text;
var serv = window.location.protocol + '//' + window.location.hostname

function list_versions(r_language, r_page) {
    text = "\n";
    for (i = 0; i < vcount; i++) {
        // text += '<dd><a href="/' + versions[i] + '/index.html?language=' + r_language + '&page=' + r_page + '" class="__ptNoRemap">' + versions[i] + "</a></dd>\n";
        text += '<dd><a href="/v' + versions[i] + '/index.html?language=' + r_language + '&page=' + r_page + '" class="__ptNoRemap">' + versions[i] + "</a></dd>\n";
    }
    text += '<dd><a href="/v' + stable_version + '/index.html?language=' + r_language + '&page=' + r_page + '" class="__ptNoRemap">stable' + "</a></dd>\n";
    // text += '<dd><a href="/index.html" class="__ptNoRemap">latest' + "</a></dd>\n";
    text += '<dd><a href="/index.html?language=' + r_language + '&page=' + r_page + '" class="__ptNoRemap">latest' + "</a></dd>\n";
    document.getElementById("select_version").innerHTML += text;
}
