name: Manual Check and Basic Build

on:
  workflow_dispatch:

jobs:
  lint_rst_and_basic_build:
    name: Check with LintRST and Basic Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint Test RST Files
      run: python ./setup.py test rst
    - name: Setup for Build
      run: |
        export SPHINXBUILD=`which sphinx-build`
        mkdir _build
        mkdir docs
    - name: Build Tag Map Files
      run: |
        python ./setup.py build map
    - name: Store Tag Map Build Output File
      uses: actions/upload-artifact@v2
      with:
        name: tag_map_files
        path: docs/MusicBrainz_Picard_Tag_Map.*
        retention-days: 5
    - name: Build HTML Files
      run: |
        python ./setup.py clean html
        python ./setup.py build html
    - name: Store HTML Build Output File
      uses: actions/upload-artifact@v2
      with:
        name: html_files
        path: docs/*.zip
        retention-days: 5
    - name: Build EPUB File
      run: |
        python ./setup.py clean epub
        python ./setup.py build epub
    - name: Store ePub Build Output File
      uses: actions/upload-artifact@v2
      with:
        name: epub_file
        path: docs/*.epub
        retention-days: 5
    - name: Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install latexmk
        sudo apt-get install xzdec
        sudo apt-get install texlive
        sudo apt-get install texlive-fonts-extra
        sudo apt-get install texlive-latex-extra
        sudo apt-get install texlive-luatex
        sudo apt-get install xindy
    - name: Build PDF File
      run: |
        python ./setup.py clean pdf
        python ./setup.py build pdf
    - name: Store PDF Build Output File
      uses: actions/upload-artifact@v2
      with:
        name: pdf_file
        path: docs/*.pdf
        retention-days: 5
    - name: Display Variables Passed to Publish Action
      run: |
        cat docs/__init__.py
